spring.datasource.url=jdbc:postgresql://localhost:5432/chat
spring.datasource.username=chat
spring.datasource.password=chat
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
  #validate
spring.jpa.open-in-view=false
